config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # SEE ALL PETS
  get 'pets', to: 'pets#index'

  # ADD A PET
  get 'pets/new', to: 'pets#new', as: 'new_pet'
  post 'pets', to: 'pets#create'

  # SEE DETAILS ABOUT ONE PET
  get 'pets/:id', to: 'pets#show', as: 'pet'

  # UPDATE PET
  get 'pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
  patch 'pets/:id', to: 'pets#update'

  delete 'pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: { in: ['dog', 'hipo', 'elephant', 'mouse']}

  def found_days_ago
    (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    # retrieve our pet
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    pet = Pet.new(pet_params)
    pet.save
    redirect_to pet_path(pet) #=> /pets/12423452
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    pet = Pet.find(params[:id])
    pet.update(pet_params)
    redirect_to pet_path(pet) #=> /pets/12423452
  end

  def destroy
    pet = Pet.find(params[:id])
    pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :found_on, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1182</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :found_on %>
  <%= f.date_field :found_on %>
  <%= f.label :species %>
  <%= f.select :species, collection: ['dog', 'hipo', 'elephant', 'mouse']  %>
  <%= f.submit %>
<% end %>

<% if pet.id.nil? %>
  <%= link_to 'Cancel', pets_path %>
<% else %>
  <%= link_to 'Cancel', pet_path(pet) %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>Lost and Found</h1>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <p><%= link_to pet.name, pet_path(pet) %></p>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p>Address: <%= @pet.address %></p>
<p>Species: <%= @pet.species %></p>
<p><%= @pet.found_days_ago %> days ago</p>

<%= link_to 'Back to index', pets_path %> |
<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Remove this pet', pet_path(@pet), data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?' }  %>